title: Salil Wadnerkar
logo: "/images/logo.png?raw=true"
description: >
  My thoughts on technologies
  <br><br>
  Primarily on popular programming languages and web frameworks
  <br><br>
  <a href="https://www.linkedin.com/in/salil-wadnerkar/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-slate
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
